version: 2.1
orbs:
jobs:
  validate:
    docker:
      - image: erikgoldmanpanther/auxiliary-builder:latest
    steps:
      - checkout
      - run: find .
      - run: find . -iname '*.tf' | xargs -I {} terraform validate {}
      - run: terraform fmt -check -recursive ./terraform
      - run: find . -iname '*.tf' | xargs -I {} tflint {}
      - run: find ./cloudformation -iname '*.yml' | xargs -I {} cfn-lint {}

workflows:
  validate:
    jobs:
      - validate
